# This file contains the configuration values for the Jenkins Helm chart.
controller:
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - pipeline-aws
    - github
    - job-dsl
# This script will create a seed job that will generate the pipeline job for the Node.js GitOps CI/CD.
  initScripts:
    seed-job.groovy: |
      import javaposse.jobdsl.plugin.ExecuteDslScripts

      println("⚙️  Starting Seed Job execution...")

      def jobDslScript = '''
      pipelineJob("nodejs-gitops-ci") {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/NaghamMohamedMohamed/GitOps-Pipeline-On-AWS-Terraform.git")
                }
                branches("*/main")
              }
            }
            scriptPath("Jenkinsfile")
          }
        }
        triggers {
          githubPush()
        }
      }
      '''

      def job = new ExecuteDslScripts()
      job.setScriptText(jobDslScript)
      job.setUseScriptText(true)
      job.run()

      println("✅ Seed job created.")

persistence:
  enabled: true
  existingClaim: "jenkins-pvc"              