apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
spec:
  serviceAccountName: kaniko-sa
  automountServiceAccountToken: true
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - cat
    tty: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
      - name: kaniko-cache
        mountPath: /kaniko/cache
  volumes:
  - name: kaniko-cache
    emptyDir: {}