apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: gitops-gp-mysql-secret
        property: username
        
    - secretKey: mysql-password
      remoteRef:
        key: gitops-gp-mysql-secret
        property: password

    - secretKey: mysql-root-password
      remoteRef:
        key: gitops-gp-mysql-secret
        property: mysql-root-password
